/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { OpenmailSDKCore } from "../core.js";
import { appendForm, encodeSimple, normalizeBlob } from "../lib/encodings.js";
import {
  bytesToBlob,
  getContentTypeFromFileName,
  readableStreamToArrayBuffer,
} from "../lib/files.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { OpenmailSDKError } from "../models/errors/openmail-sdk-error.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { isBlobLike } from "../types/blobs.js";
import { Result } from "../types/fp.js";
import { isReadableStream } from "../types/streams.js";

/**
 * Send email
 *
 * @remarks
 * Send an email from an inbox. Requires Idempotency-Key header. Use threadId to reply to an existing thread. When replying on a thread where your inbox was CC'd (deliveryRole cc), the original sender is automatically CC'd.
 */
export function messagesSendEmailMultipart(
  client: OpenmailSDKCore,
  request: operations.SendEmailMultipartRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.SendEmailMultipartResponse,
    | errors.ErrorT
    | OpenmailSDKError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: OpenmailSDKCore,
  request: operations.SendEmailMultipartRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.SendEmailMultipartResponse,
      | errors.ErrorT
      | OpenmailSDKError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      z.parse(operations.SendEmailMultipartRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = new FormData();

  appendForm(body, "body", payload.body.body);
  appendForm(body, "to", payload.body.to);
  if (payload.body.attachments !== undefined) {
    for (const fileItem of payload.body.attachments ?? []) {
      if (isBlobLike(fileItem)) {
        const file = fileItem;
        const blob = await normalizeBlob(file);
        const name = "name" in file ? (file.name as string) : undefined;
        appendForm(body, "attachments", blob, name);
      } else if (isReadableStream(fileItem.content)) {
        const buffer = await readableStreamToArrayBuffer(fileItem.content);
        const contentType = getContentTypeFromFileName(fileItem.fileName)
          || "application/octet-stream";
        appendForm(
          body,
          "attachments",
          bytesToBlob(buffer, contentType),
          fileItem.fileName,
        );
      } else {
        const contentType = getContentTypeFromFileName(fileItem.fileName)
          || "application/octet-stream";
        appendForm(
          body,
          "attachments",
          bytesToBlob(fileItem.content, contentType),
          fileItem.fileName,
        );
      }
    }
  }
  if (payload.body.bodyHtml !== undefined) {
    appendForm(body, "bodyHtml", payload.body.bodyHtml);
  }
  if (payload.body.cc !== undefined) {
    appendForm(body, "cc", payload.body.cc);
  }
  if (payload.body.includeQuote !== undefined) {
    appendForm(body, "includeQuote", payload.body.includeQuote);
  }
  if (payload.body.replyTo !== undefined) {
    appendForm(body, "replyTo", payload.body.replyTo);
  }
  if (payload.body.subject !== undefined) {
    appendForm(body, "subject", payload.body.subject);
  }
  if (payload.body.threadId !== undefined) {
    appendForm(body, "threadId", payload.body.threadId);
  }

  const pathParams = {
    id: encodeSimple("id", payload.id, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path = pathToFunc("/v1/inboxes/{id}/send")(pathParams);

  const headers = new Headers(compactMap({
    Accept: "application/json",
    "idempotency-key": encodeSimple(
      "idempotency-key",
      payload["idempotency-key"],
      { explode: false, charEncoding: "none" },
    ),
  }));

  const secConfig = await extractSecurity(client._options.bearerAuth);
  const securityInput = secConfig == null ? {} : { bearerAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "sendEmail_multipart",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.bearerAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || {
        strategy: "backoff",
        backoff: {
          initialInterval: 500,
          maxInterval: 60000,
          exponent: 1.5,
          maxElapsedTime: 3600000,
        },
        retryConnectionErrors: true,
      }
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["5XX", "429"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.SendEmailMultipartResponse,
    | errors.ErrorT
    | OpenmailSDKError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.SendEmailMultipartResponse$inboundSchema),
    M.jsonErr([400, 402, 403, 404, 422, 429], errors.ErrorT$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
