/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { attachmentsGetAttachmentText } from "../funcs/attachments-get-attachment-text.js";
import { attachmentsGetAttachment } from "../funcs/attachments-get-attachment.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Attachments extends ClientSDK {
  /**
   * Get attachment
   *
   * @remarks
   * Returns a 302 redirect to a signed URL for the attachment.
   */
  async getAttachment(
    request: operations.GetAttachmentRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(attachmentsGetAttachment(
      this,
      request,
      options,
    ));
  }

  /**
   * Extract attachment text
   *
   * @remarks
   * Extracts and returns the plain text content of an attachment. Supports PDF, DOCX, XLSX, PPTX, images (via OCR), and other common formats. The result is cached on the message after the first extraction.
   */
  async getAttachmentText(
    request: operations.GetAttachmentTextRequest,
    options?: RequestOptions,
  ): Promise<operations.GetAttachmentTextResponse> {
    return unwrapAsync(attachmentsGetAttachmentText(
      this,
      request,
      options,
    ));
  }
}
