/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { inboxesCreateInbox } from "../funcs/inboxes-create-inbox.js";
import { inboxesDeleteInbox } from "../funcs/inboxes-delete-inbox.js";
import { inboxesGetInbox } from "../funcs/inboxes-get-inbox.js";
import { inboxesListInboxes } from "../funcs/inboxes-list-inboxes.js";
import { inboxesRotateInboxWebhookSecret } from "../funcs/inboxes-rotate-inbox-webhook-secret.js";
import { inboxesTestInboxWebhook } from "../funcs/inboxes-test-inbox-webhook.js";
import { inboxesUpdateInbox } from "../funcs/inboxes-update-inbox.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Inboxes extends ClientSDK {
  /**
   * Create inbox
   *
   * @remarks
   * Create a new email inbox. Optionally set a sender display name.
   */
  async createInbox(
    request: operations.CreateInboxRequest,
    options?: RequestOptions,
  ): Promise<models.Inbox> {
    return unwrapAsync(inboxesCreateInbox(
      this,
      request,
      options,
    ));
  }

  /**
   * List inboxes
   *
   * @remarks
   * List all inboxes for your account. Supports pagination.
   */
  async listInboxes(
    request?: operations.ListInboxesRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListInboxesResponse, { offset: number }>> {
    return unwrapResultIterator(inboxesListInboxes(
      this,
      request,
      options,
    ));
  }

  /**
   * Get inbox
   *
   * @remarks
   * Retrieve a single inbox by its ID, including its address, display name, and creation time.
   */
  async getInbox(
    request: operations.GetInboxRequest,
    options?: RequestOptions,
  ): Promise<models.Inbox> {
    return unwrapAsync(inboxesGetInbox(
      this,
      request,
      options,
    ));
  }

  /**
   * Update inbox
   *
   * @remarks
   * Update an inbox's settings, such as the sender display name shown in the From header.
   */
  async updateInbox(
    request: operations.UpdateInboxRequest,
    options?: RequestOptions,
  ): Promise<models.Inbox> {
    return unwrapAsync(inboxesUpdateInbox(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete inbox
   *
   * @remarks
   * Permanently delete an inbox and stop delivery to its address. This action cannot be undone.
   */
  async deleteInbox(
    request: operations.DeleteInboxRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(inboxesDeleteInbox(
      this,
      request,
      options,
    ));
  }

  /**
   * Rotate webhook secret
   *
   * @remarks
   * Generate a new signing secret for this inbox's webhook. The inbox must already have a webhook URL set. The previous secret is invalidated immediately.
   */
  async rotateInboxWebhookSecret(
    request: operations.RotateInboxWebhookSecretRequest,
    options?: RequestOptions,
  ): Promise<operations.RotateInboxWebhookSecretResponse> {
    return unwrapAsync(inboxesRotateInboxWebhookSecret(
      this,
      request,
      options,
    ));
  }

  /**
   * Send test webhook
   *
   * @remarks
   * Send a signed test event to this inbox's webhook URL. Requires a webhook URL (and signing secret) to already be set on the inbox.
   */
  async testInboxWebhook(
    request: operations.TestInboxWebhookRequest,
    options?: RequestOptions,
  ): Promise<operations.TestInboxWebhookResponse> {
    return unwrapAsync(inboxesTestInboxWebhook(
      this,
      request,
      options,
    ));
  }
}
