/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesListMessages } from "../funcs/messages-list-messages.js";
import { messagesSendEmailMultipart } from "../funcs/messages-send-email-multipart.js";
import { messagesSendEmail } from "../funcs/messages-send-email.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Messages extends ClientSDK {
  /**
   * Send email
   *
   * @remarks
   * Send an email from an inbox. Requires Idempotency-Key header. Use threadId to reply to an existing thread. When replying on a thread where your inbox was CC'd (deliveryRole cc), the original sender is automatically CC'd.
   */
  async sendEmail(
    request: operations.SendEmailRequest,
    options?: RequestOptions,
  ): Promise<operations.SendEmailResponse> {
    return unwrapAsync(messagesSendEmail(
      this,
      request,
      options,
    ));
  }

  /**
   * Send email
   *
   * @remarks
   * Send an email from an inbox. Requires Idempotency-Key header. Use threadId to reply to an existing thread. When replying on a thread where your inbox was CC'd (deliveryRole cc), the original sender is automatically CC'd.
   */
  async sendEmailMultipart(
    request: operations.SendEmailMultipartRequest,
    options?: RequestOptions,
  ): Promise<operations.SendEmailMultipartResponse> {
    return unwrapAsync(messagesSendEmailMultipart(
      this,
      request,
      options,
    ));
  }

  /**
   * List messages
   *
   * @remarks
   * List all messages in an inbox, across every thread. Supports pagination for high-volume inboxes.
   */
  async listMessages(
    request: operations.ListMessagesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListMessagesResponse, { offset: number }>
  > {
    return unwrapResultIterator(messagesListMessages(
      this,
      request,
      options,
    ));
  }
}
