/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { podsCreatePod } from "../funcs/pods-create-pod.js";
import { podsDeletePod } from "../funcs/pods-delete-pod.js";
import { podsGetPod } from "../funcs/pods-get-pod.js";
import { podsListPods } from "../funcs/pods-list-pods.js";
import { podsUpdatePod } from "../funcs/pods-update-pod.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Pods extends ClientSDK {
  /**
   * Create pod
   *
   * @remarks
   * Create a new pod (an isolated sub-account for one of your end users or tenants). Pass your own `clientId` to map the pod to a record in your system and address it later without storing the OpenMail ID.
   */
  async createPod(
    request: operations.CreatePodRequest,
    options?: RequestOptions,
  ): Promise<models.Pod> {
    return unwrapAsync(podsCreatePod(
      this,
      request,
      options,
    ));
  }

  /**
   * List pods
   *
   * @remarks
   * List all pods for your account. The default pod is always returned first. Supports pagination.
   */
  async listPods(
    request?: operations.ListPodsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListPodsResponse, { offset: number }>> {
    return unwrapResultIterator(podsListPods(
      this,
      request,
      options,
    ));
  }

  /**
   * Get pod
   *
   * @remarks
   * Retrieve a single pod by its OpenMail ID or your own `clientId`.
   */
  async getPod(
    request: operations.GetPodRequest,
    options?: RequestOptions,
  ): Promise<models.Pod> {
    return unwrapAsync(podsGetPod(
      this,
      request,
      options,
    ));
  }

  /**
   * Update pod
   *
   * @remarks
   * Update a pod's `clientId` or `name`. Only the fields you include are changed.
   */
  async updatePod(
    request: operations.UpdatePodRequest,
    options?: RequestOptions,
  ): Promise<models.Pod> {
    return unwrapAsync(podsUpdatePod(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete pod
   *
   * @remarks
   * Permanently delete a pod. The pod must be empty (no inboxes or pod-scoped domains) and cannot be the default pod.
   */
  async deletePod(
    request: operations.DeletePodRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(podsDeletePod(
      this,
      request,
      options,
    ));
  }
}
