/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Attachments } from "./attachments.js";
import { Inboxes } from "./inboxes.js";
import { Messages } from "./messages.js";
import { Pods } from "./pods.js";
import { Threads } from "./threads.js";

export class OpenmailSDK extends ClientSDK {
  private _pods?: Pods;
  get pods(): Pods {
    return (this._pods ??= new Pods(this._options));
  }

  private _inboxes?: Inboxes;
  get inboxes(): Inboxes {
    return (this._inboxes ??= new Inboxes(this._options));
  }

  private _messages?: Messages;
  get messages(): Messages {
    return (this._messages ??= new Messages(this._options));
  }

  private _attachments?: Attachments;
  get attachments(): Attachments {
    return (this._attachments ??= new Attachments(this._options));
  }

  private _threads?: Threads;
  get threads(): Threads {
    return (this._threads ??= new Threads(this._options));
  }
}
