/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { threadsGetThreadMessages } from "../funcs/threads-get-thread-messages.js";
import { threadsListThreads } from "../funcs/threads-list-threads.js";
import { threadsUpdateThread } from "../funcs/threads-update-thread.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Threads extends ClientSDK {
  /**
   * List threads
   *
   * @remarks
   * List threads for an inbox. Use is_read to filter by read status — for example, ?is_read=false returns only unread threads.
   */
  async listThreads(
    request: operations.ListThreadsRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListThreadsResponse, { offset: number }>> {
    return unwrapResultIterator(threadsListThreads(
      this,
      request,
      options,
    ));
  }

  /**
   * Get thread messages
   *
   * @remarks
   * Retrieve a thread and all of its messages in order, with read status and full message content.
   */
  async getThreadMessages(
    request: operations.GetThreadMessagesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetThreadMessagesResponse> {
    return unwrapAsync(threadsGetThreadMessages(
      this,
      request,
      options,
    ));
  }

  /**
   * Update thread
   *
   * @remarks
   * Update a thread's read status. Use this to mark a thread as read after your agent has processed it, or as unread to re-queue it for later processing.
   */
  async updateThread(
    request: operations.UpdateThreadRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateThreadResponse> {
    return unwrapAsync(threadsUpdateThread(
      this,
      request,
      options,
    ));
  }
}
