/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @openmail/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx podsCreatePod.example.ts
 */

import { OpenmailSDK } from "@openmail/sdk";

const openmailSDK = new OpenmailSDK({
  bearerAuth: process.env["OPENMAILSDK_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await openmailSDK.pods.createPod({});

  console.log(result);
}

main().catch(console.error);
