/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateInboxRequest = {
  /**
   * Inbox local part (default: random)
   */
  mailboxName?: string | undefined;
  /**
   * Sender display name shown in the From header
   */
  displayName?: string | undefined;
  /**
   * Domain for the inbox address. Defaults to your account domain (e.g. `openmail.sh`). Pass a verified custom domain you own to create the inbox on it (e.g. `agent-mail.example.com`). The domain must already be added and verified for your account; the account default never switches automatically.
   */
  domain?: string | undefined;
  /**
   * URL to receive signed webhook events for this inbox (e.g. inbound mail). Overrides the account-level webhook for this inbox only. A signing secret is generated and returned once in the response body.
   */
  webhookUrl?: string | undefined;
  /**
   * Pod to create the inbox in. Accepts the pod ID or your own `clientId`. Omit to place the inbox in your account's default pod.
   */
  podId?: string | undefined;
};

/** @internal */
export type CreateInboxRequest$Outbound = {
  mailboxName?: string | undefined;
  displayName?: string | undefined;
  domain?: string | undefined;
  webhookUrl?: string | undefined;
  podId?: string | undefined;
};

/** @internal */
export const CreateInboxRequest$outboundSchema: z.ZodMiniType<
  CreateInboxRequest$Outbound,
  CreateInboxRequest
> = z.object({
  mailboxName: z.optional(z.string()),
  displayName: z.optional(z.string()),
  domain: z.optional(z.string()),
  webhookUrl: z.optional(z.string()),
  podId: z.optional(z.string()),
});

export function createInboxRequestToJSON(
  createInboxRequest: CreateInboxRequest,
): string {
  return JSON.stringify(
    CreateInboxRequest$outboundSchema.parse(createInboxRequest),
  );
}
