/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreatePodRequest = {
  /**
   * Your own stable identifier for this pod (e.g. your user/tenant ID). Must be unique within your account. Use it in place of the pod ID on any pod or inbox endpoint.
   */
  clientId?: string | null | undefined;
  /**
   * Human-readable label shown in the console.
   */
  name?: string | null | undefined;
};

/** @internal */
export type CreatePodRequest$Outbound = {
  clientId?: string | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const CreatePodRequest$outboundSchema: z.ZodMiniType<
  CreatePodRequest$Outbound,
  CreatePodRequest
> = z.object({
  clientId: z.optional(z.nullable(z.string())),
  name: z.optional(z.nullable(z.string())),
});

export function createPodRequestToJSON(
  createPodRequest: CreatePodRequest,
): string {
  return JSON.stringify(
    CreatePodRequest$outboundSchema.parse(createPodRequest),
  );
}
