/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteInboxRequest = {
  id: string;
};

/** @internal */
export type DeleteInboxRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteInboxRequest$outboundSchema: z.ZodMiniType<
  DeleteInboxRequest$Outbound,
  DeleteInboxRequest
> = z.object({
  id: z.string(),
});

export function deleteInboxRequestToJSON(
  deleteInboxRequest: DeleteInboxRequest,
): string {
  return JSON.stringify(
    DeleteInboxRequest$outboundSchema.parse(deleteInboxRequest),
  );
}
