/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeletePodRequest = {
  /**
   * Pod ID or your own `clientId`
   */
  id: string;
};

/** @internal */
export type DeletePodRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeletePodRequest$outboundSchema: z.ZodMiniType<
  DeletePodRequest$Outbound,
  DeletePodRequest
> = z.object({
  id: z.string(),
});

export function deletePodRequestToJSON(
  deletePodRequest: DeletePodRequest,
): string {
  return JSON.stringify(
    DeletePodRequest$outboundSchema.parse(deletePodRequest),
  );
}
