/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetInboxRequest = {
  id: string;
};

/** @internal */
export type GetInboxRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetInboxRequest$outboundSchema: z.ZodMiniType<
  GetInboxRequest$Outbound,
  GetInboxRequest
> = z.object({
  id: z.string(),
});

export function getInboxRequestToJSON(
  getInboxRequest: GetInboxRequest,
): string {
  return JSON.stringify(GetInboxRequest$outboundSchema.parse(getInboxRequest));
}
