/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetThreadMessagesRequest = {
  id: string;
};

/**
 * Thread with messages
 */
export type GetThreadMessagesResponse = {
  threadId?: string | undefined;
  subject?: string | undefined;
  /**
   * Whether the thread has been marked as read
   */
  isRead?: boolean | undefined;
  data?: Array<models.Message> | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export type GetThreadMessagesRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetThreadMessagesRequest$outboundSchema: z.ZodMiniType<
  GetThreadMessagesRequest$Outbound,
  GetThreadMessagesRequest
> = z.object({
  id: z.string(),
});

export function getThreadMessagesRequestToJSON(
  getThreadMessagesRequest: GetThreadMessagesRequest,
): string {
  return JSON.stringify(
    GetThreadMessagesRequest$outboundSchema.parse(getThreadMessagesRequest),
  );
}

/** @internal */
export const GetThreadMessagesResponse$inboundSchema: z.ZodMiniType<
  GetThreadMessagesResponse,
  unknown
> = z.catchall(
  z.object({
    threadId: types.optional(types.string()),
    subject: types.optional(types.string()),
    isRead: types.optional(types.boolean()),
    data: types.optional(z.array(models.Message$inboundSchema)),
  }),
  z.any(),
);

export function getThreadMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetThreadMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetThreadMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetThreadMessagesResponse' from JSON`,
  );
}
