/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetAttachmentRequest = {
  messageId: string;
  filename: string;
};

/** @internal */
export type GetAttachmentRequest$Outbound = {
  messageId: string;
  filename: string;
};

/** @internal */
export const GetAttachmentRequest$outboundSchema: z.ZodMiniType<
  GetAttachmentRequest$Outbound,
  GetAttachmentRequest
> = z.object({
  messageId: z.string(),
  filename: z.string(),
});

export function getAttachmentRequestToJSON(
  getAttachmentRequest: GetAttachmentRequest,
): string {
  return JSON.stringify(
    GetAttachmentRequest$outboundSchema.parse(getAttachmentRequest),
  );
}
