/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetPodRequest = {
  /**
   * Pod ID or your own `clientId`
   */
  id: string;
};

/** @internal */
export type GetPodRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetPodRequest$outboundSchema: z.ZodMiniType<
  GetPodRequest$Outbound,
  GetPodRequest
> = z.object({
  id: z.string(),
});

export function getPodRequestToJSON(getPodRequest: GetPodRequest): string {
  return JSON.stringify(GetPodRequest$outboundSchema.parse(getPodRequest));
}
