/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetAttachmentTextRequest = {
  messageId: string;
  filename: string;
};

/**
 * Extracted text content
 */
export type GetAttachmentTextResponse = {
  filename?: string | undefined;
  contentType?: string | undefined;
  /**
   * Method used to extract text (e.g. pdf, docx, ocr)
   */
  extractionMethod?: string | undefined;
  text?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export type GetAttachmentTextRequest$Outbound = {
  messageId: string;
  filename: string;
};

/** @internal */
export const GetAttachmentTextRequest$outboundSchema: z.ZodMiniType<
  GetAttachmentTextRequest$Outbound,
  GetAttachmentTextRequest
> = z.object({
  messageId: z.string(),
  filename: z.string(),
});

export function getAttachmentTextRequestToJSON(
  getAttachmentTextRequest: GetAttachmentTextRequest,
): string {
  return JSON.stringify(
    GetAttachmentTextRequest$outboundSchema.parse(getAttachmentTextRequest),
  );
}

/** @internal */
export const GetAttachmentTextResponse$inboundSchema: z.ZodMiniType<
  GetAttachmentTextResponse,
  unknown
> = z.catchall(
  z.object({
    filename: types.optional(types.string()),
    contentType: types.optional(types.string()),
    extractionMethod: types.optional(types.string()),
    text: types.optional(types.string()),
  }),
  z.any(),
);

export function getAttachmentTextResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAttachmentTextResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAttachmentTextResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAttachmentTextResponse' from JSON`,
  );
}
