/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListPodsRequest = {
  /**
   * Max results to return (clamped to 100)
   */
  limit?: number | undefined;
  /**
   * Number of results to skip
   */
  offset?: number | undefined;
};

/**
 * List of pods
 */
export type ListPodsResponseBody = {
  data?: Array<models.Pod> | undefined;
  total?: number | undefined;
  [additionalProperties: string]: unknown;
};

export type ListPodsResponse = {
  result: ListPodsResponseBody;
};

/** @internal */
export type ListPodsRequest$Outbound = {
  limit: number;
  offset: number;
};

/** @internal */
export const ListPodsRequest$outboundSchema: z.ZodMiniType<
  ListPodsRequest$Outbound,
  ListPodsRequest
> = z.object({
  limit: z._default(z.int(), 50),
  offset: z._default(z.int(), 0),
});

export function listPodsRequestToJSON(
  listPodsRequest: ListPodsRequest,
): string {
  return JSON.stringify(ListPodsRequest$outboundSchema.parse(listPodsRequest));
}

/** @internal */
export const ListPodsResponseBody$inboundSchema: z.ZodMiniType<
  ListPodsResponseBody,
  unknown
> = z.catchall(
  z.object({
    data: types.optional(z.array(models.Pod$inboundSchema)),
    total: types.optional(types.number()),
  }),
  z.any(),
);

export function listPodsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListPodsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPodsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPodsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListPodsResponse$inboundSchema: z.ZodMiniType<
  ListPodsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: z.lazy(() => ListPodsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listPodsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPodsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPodsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPodsResponse' from JSON`,
  );
}
