/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListMessagesRequest = {
  limit?: number | undefined;
  offset?: number | undefined;
  direction?: models.MessageDirection | undefined;
  id: string;
};

/**
 * List of messages
 */
export type ListMessagesResponseBody = {
  data?: Array<models.Message> | undefined;
  total?: number | undefined;
  [additionalProperties: string]: unknown;
};

export type ListMessagesResponse = {
  result: ListMessagesResponseBody;
};

/** @internal */
export type ListMessagesRequest$Outbound = {
  limit: number;
  offset: number;
  direction?: string | undefined;
  id: string;
};

/** @internal */
export const ListMessagesRequest$outboundSchema: z.ZodMiniType<
  ListMessagesRequest$Outbound,
  ListMessagesRequest
> = z.object({
  limit: z._default(z.int(), 50),
  offset: z._default(z.int(), 0),
  direction: z.optional(models.MessageDirection$outboundSchema),
  id: z.string(),
});

export function listMessagesRequestToJSON(
  listMessagesRequest: ListMessagesRequest,
): string {
  return JSON.stringify(
    ListMessagesRequest$outboundSchema.parse(listMessagesRequest),
  );
}

/** @internal */
export const ListMessagesResponseBody$inboundSchema: z.ZodMiniType<
  ListMessagesResponseBody,
  unknown
> = z.catchall(
  z.object({
    data: types.optional(z.array(models.Message$inboundSchema)),
    total: types.optional(types.number()),
  }),
  z.any(),
);

export function listMessagesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListMessagesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMessagesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMessagesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListMessagesResponse$inboundSchema: z.ZodMiniType<
  ListMessagesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: z.lazy(() => ListMessagesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMessagesResponse' from JSON`,
  );
}
