/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListInboxesRequest = {
  /**
   * Max results to return (clamped to 100)
   */
  limit?: number | undefined;
  /**
   * Number of results to skip
   */
  offset?: number | undefined;
  /**
   * Filter to inboxes in a single pod. Accepts the pod ID or your own `clientId`. An unknown value returns an empty list.
   */
  podId?: string | undefined;
};

/**
 * List of inboxes
 */
export type ListInboxesResponseBody = {
  data?: Array<models.Inbox> | undefined;
  total?: number | undefined;
  [additionalProperties: string]: unknown;
};

export type ListInboxesResponse = {
  result: ListInboxesResponseBody;
};

/** @internal */
export type ListInboxesRequest$Outbound = {
  limit: number;
  offset: number;
  podId?: string | undefined;
};

/** @internal */
export const ListInboxesRequest$outboundSchema: z.ZodMiniType<
  ListInboxesRequest$Outbound,
  ListInboxesRequest
> = z.object({
  limit: z._default(z.int(), 50),
  offset: z._default(z.int(), 0),
  podId: z.optional(z.string()),
});

export function listInboxesRequestToJSON(
  listInboxesRequest: ListInboxesRequest,
): string {
  return JSON.stringify(
    ListInboxesRequest$outboundSchema.parse(listInboxesRequest),
  );
}

/** @internal */
export const ListInboxesResponseBody$inboundSchema: z.ZodMiniType<
  ListInboxesResponseBody,
  unknown
> = z.catchall(
  z.object({
    data: types.optional(z.array(models.Inbox$inboundSchema)),
    total: types.optional(types.number()),
  }),
  z.any(),
);

export function listInboxesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListInboxesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListInboxesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInboxesResponseBody' from JSON`,
  );
}

/** @internal */
export const ListInboxesResponse$inboundSchema: z.ZodMiniType<
  ListInboxesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: z.lazy(() => ListInboxesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listInboxesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListInboxesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListInboxesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInboxesResponse' from JSON`,
  );
}
