/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Filter by read status. true = read threads only, false = unread threads only. Omit to return all.
 */
export const IsRead = {
  True: "true",
  False: "false",
} as const;
/**
 * Filter by read status. true = read threads only, false = unread threads only. Omit to return all.
 */
export type IsRead = ClosedEnum<typeof IsRead>;

export type ListThreadsRequest = {
  limit?: number | undefined;
  offset?: number | undefined;
  /**
   * Filter by read status. true = read threads only, false = unread threads only. Omit to return all.
   */
  isRead?: IsRead | undefined;
  id: string;
};

/**
 * List of threads
 */
export type ListThreadsResponseBody = {
  data?: Array<models.Thread> | undefined;
  total?: number | undefined;
  [additionalProperties: string]: unknown;
};

export type ListThreadsResponse = {
  result: ListThreadsResponseBody;
};

/** @internal */
export const IsRead$outboundSchema: z.ZodMiniEnum<typeof IsRead> = z.enum(
  IsRead,
);

/** @internal */
export type ListThreadsRequest$Outbound = {
  limit: number;
  offset: number;
  is_read?: string | undefined;
  id: string;
};

/** @internal */
export const ListThreadsRequest$outboundSchema: z.ZodMiniType<
  ListThreadsRequest$Outbound,
  ListThreadsRequest
> = z.pipe(
  z.object({
    limit: z._default(z.int(), 50),
    offset: z._default(z.int(), 0),
    isRead: z.optional(IsRead$outboundSchema),
    id: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      isRead: "is_read",
    });
  }),
);

export function listThreadsRequestToJSON(
  listThreadsRequest: ListThreadsRequest,
): string {
  return JSON.stringify(
    ListThreadsRequest$outboundSchema.parse(listThreadsRequest),
  );
}

/** @internal */
export const ListThreadsResponseBody$inboundSchema: z.ZodMiniType<
  ListThreadsResponseBody,
  unknown
> = z.catchall(
  z.object({
    data: types.optional(z.array(models.Thread$inboundSchema)),
    total: types.optional(types.number()),
  }),
  z.any(),
);

export function listThreadsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListThreadsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListThreadsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListThreadsResponseBody' from JSON`,
  );
}

/** @internal */
export const ListThreadsResponse$inboundSchema: z.ZodMiniType<
  ListThreadsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: z.lazy(() => ListThreadsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listThreadsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListThreadsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListThreadsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListThreadsResponse' from JSON`,
  );
}
