/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RotateInboxWebhookSecretRequest = {
  id: string;
};

/**
 * New signing secret
 */
export type RotateInboxWebhookSecretResponse = {
  webhookSecret: string;
  [additionalProperties: string]: unknown;
};

/** @internal */
export type RotateInboxWebhookSecretRequest$Outbound = {
  id: string;
};

/** @internal */
export const RotateInboxWebhookSecretRequest$outboundSchema: z.ZodMiniType<
  RotateInboxWebhookSecretRequest$Outbound,
  RotateInboxWebhookSecretRequest
> = z.object({
  id: z.string(),
});

export function rotateInboxWebhookSecretRequestToJSON(
  rotateInboxWebhookSecretRequest: RotateInboxWebhookSecretRequest,
): string {
  return JSON.stringify(
    RotateInboxWebhookSecretRequest$outboundSchema.parse(
      rotateInboxWebhookSecretRequest,
    ),
  );
}

/** @internal */
export const RotateInboxWebhookSecretResponse$inboundSchema: z.ZodMiniType<
  RotateInboxWebhookSecretResponse,
  unknown
> = z.catchall(
  z.object({
    webhookSecret: types.string(),
  }),
  z.any(),
);

export function rotateInboxWebhookSecretResponseFromJSON(
  jsonString: string,
): SafeParseResult<RotateInboxWebhookSecretResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RotateInboxWebhookSecretResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RotateInboxWebhookSecretResponse' from JSON`,
  );
}
