/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Attachment = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type SendEmailMultipartRequestBody = {
  to: string;
  /**
   * Required for new threads. Optional when threadId is set — the thread subject is used automatically (with Re: prefix).
   */
  subject?: string | undefined;
  /**
   * Email body. Plain text or HTML — HTML is auto-detected and rendered, with a plain-text fallback generated automatically.
   */
  body: string;
  /**
   * Provide only when the plain-text and HTML versions must differ. Omit for normal sends — put HTML in `body` instead.
   */
  bodyHtml?: string | undefined;
  /**
   * Thread ID for replies
   */
  threadId?: string | undefined;
  /**
   * When replying with threadId, append a quoted copy of the previous message to the body. Defaults to true. Set false to send only your reply text.
   */
  includeQuote?: boolean | undefined;
  /**
   * Optional. Address that replies should be routed to (set as the `Reply-To` MIME header). Free plan: must be the address of an inbox you own in OpenMail. Pro plan or higher: any valid email address.
   */
  replyTo?: string | undefined;
  /**
   * Optional CC recipients.
   */
  cc?: Array<string> | undefined;
  /**
   * File attachments (max 25 MB total per email)
   */
  attachments?: Array<Attachment> | undefined;
};

export type SendEmailMultipartRequest = {
  id: string;
  /**
   * Unique key for idempotent sends (e.g. UUID)
   */
  idempotencyKey?: string | undefined;
  body: SendEmailMultipartRequestBody;
};

export const SendEmailMultipartStatus = {
  Pending: "pending",
  Sent: "sent",
  Failed: "failed",
} as const;
export type SendEmailMultipartStatus = OpenEnum<
  typeof SendEmailMultipartStatus
>;

/**
 * Email sent (or idempotent replay)
 */
export type SendEmailMultipartResponse = {
  messageId?: string | undefined;
  threadId?: string | undefined;
  providerMessageId?: string | undefined;
  status?: SendEmailMultipartStatus | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export type Attachment$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Attachment$outboundSchema: z.ZodMiniType<
  Attachment$Outbound,
  Attachment
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function attachmentToJSON(attachment: Attachment): string {
  return JSON.stringify(Attachment$outboundSchema.parse(attachment));
}

/** @internal */
export type SendEmailMultipartRequestBody$Outbound = {
  to: string;
  subject?: string | undefined;
  body: string;
  bodyHtml?: string | undefined;
  threadId?: string | undefined;
  includeQuote?: boolean | undefined;
  replyTo?: string | undefined;
  cc?: Array<string> | undefined;
  attachments?: Array<Attachment$Outbound> | undefined;
};

/** @internal */
export const SendEmailMultipartRequestBody$outboundSchema: z.ZodMiniType<
  SendEmailMultipartRequestBody$Outbound,
  SendEmailMultipartRequestBody
> = z.object({
  to: z.string(),
  subject: z.optional(z.string()),
  body: z.string(),
  bodyHtml: z.optional(z.string()),
  threadId: z.optional(z.string()),
  includeQuote: z.optional(z.boolean()),
  replyTo: z.optional(z.string()),
  cc: z.optional(z.array(z.string())),
  attachments: z.optional(z.array(z.lazy(() => Attachment$outboundSchema))),
});

export function sendEmailMultipartRequestBodyToJSON(
  sendEmailMultipartRequestBody: SendEmailMultipartRequestBody,
): string {
  return JSON.stringify(
    SendEmailMultipartRequestBody$outboundSchema.parse(
      sendEmailMultipartRequestBody,
    ),
  );
}

/** @internal */
export type SendEmailMultipartRequest$Outbound = {
  id: string;
  "idempotency-key"?: string | undefined;
  body: SendEmailMultipartRequestBody$Outbound;
};

/** @internal */
export const SendEmailMultipartRequest$outboundSchema: z.ZodMiniType<
  SendEmailMultipartRequest$Outbound,
  SendEmailMultipartRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: z.lazy(() => SendEmailMultipartRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
    });
  }),
);

export function sendEmailMultipartRequestToJSON(
  sendEmailMultipartRequest: SendEmailMultipartRequest,
): string {
  return JSON.stringify(
    SendEmailMultipartRequest$outboundSchema.parse(sendEmailMultipartRequest),
  );
}

/** @internal */
export const SendEmailMultipartStatus$inboundSchema: z.ZodMiniType<
  SendEmailMultipartStatus,
  unknown
> = openEnums.inboundSchema(SendEmailMultipartStatus);

/** @internal */
export const SendEmailMultipartResponse$inboundSchema: z.ZodMiniType<
  SendEmailMultipartResponse,
  unknown
> = z.catchall(
  z.object({
    messageId: types.optional(types.string()),
    threadId: types.optional(types.string()),
    providerMessageId: types.optional(types.string()),
    status: types.optional(SendEmailMultipartStatus$inboundSchema),
  }),
  z.any(),
);

export function sendEmailMultipartResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendEmailMultipartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendEmailMultipartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendEmailMultipartResponse' from JSON`,
  );
}
