/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SendEmailRequestBody = {
  to: string;
  /**
   * Required for new threads. Optional when threadId is set — the thread subject is used automatically (with Re: prefix).
   */
  subject?: string | undefined;
  /**
   * Email body. Plain text or HTML — HTML is auto-detected and rendered, with a plain-text fallback generated automatically.
   */
  body: string;
  /**
   * Provide only when the plain-text and HTML versions must differ. Omit for normal sends — put HTML in `body` instead.
   */
  bodyHtml?: string | undefined;
  /**
   * Thread ID for replies
   */
  threadId?: string | undefined;
  /**
   * When replying with threadId, append a quoted copy of the previous message to the body. Defaults to true. Set false to send only your reply text.
   */
  includeQuote?: boolean | undefined;
  /**
   * Optional. Address that replies should be routed to (set as the `Reply-To` MIME header). Free plan: must be the address of an inbox you own in OpenMail. Pro plan or higher: any valid email address.
   */
  replyTo?: string | undefined;
  /**
   * Optional CC recipients.
   */
  cc?: Array<string> | undefined;
};

export type SendEmailRequest = {
  id: string;
  /**
   * Unique key for idempotent sends (e.g. UUID)
   */
  idempotencyKey?: string | undefined;
  body: SendEmailRequestBody;
};

export const SendEmailStatus = {
  Pending: "pending",
  Sent: "sent",
  Failed: "failed",
} as const;
export type SendEmailStatus = OpenEnum<typeof SendEmailStatus>;

/**
 * Email sent (or idempotent replay)
 */
export type SendEmailResponse = {
  messageId?: string | undefined;
  threadId?: string | undefined;
  providerMessageId?: string | undefined;
  status?: SendEmailStatus | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export type SendEmailRequestBody$Outbound = {
  to: string;
  subject?: string | undefined;
  body: string;
  bodyHtml?: string | undefined;
  threadId?: string | undefined;
  includeQuote?: boolean | undefined;
  replyTo?: string | undefined;
  cc?: Array<string> | undefined;
};

/** @internal */
export const SendEmailRequestBody$outboundSchema: z.ZodMiniType<
  SendEmailRequestBody$Outbound,
  SendEmailRequestBody
> = z.object({
  to: z.string(),
  subject: z.optional(z.string()),
  body: z.string(),
  bodyHtml: z.optional(z.string()),
  threadId: z.optional(z.string()),
  includeQuote: z.optional(z.boolean()),
  replyTo: z.optional(z.string()),
  cc: z.optional(z.array(z.string())),
});

export function sendEmailRequestBodyToJSON(
  sendEmailRequestBody: SendEmailRequestBody,
): string {
  return JSON.stringify(
    SendEmailRequestBody$outboundSchema.parse(sendEmailRequestBody),
  );
}

/** @internal */
export type SendEmailRequest$Outbound = {
  id: string;
  "idempotency-key"?: string | undefined;
  body: SendEmailRequestBody$Outbound;
};

/** @internal */
export const SendEmailRequest$outboundSchema: z.ZodMiniType<
  SendEmailRequest$Outbound,
  SendEmailRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: z.lazy(() => SendEmailRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
    });
  }),
);

export function sendEmailRequestToJSON(
  sendEmailRequest: SendEmailRequest,
): string {
  return JSON.stringify(
    SendEmailRequest$outboundSchema.parse(sendEmailRequest),
  );
}

/** @internal */
export const SendEmailStatus$inboundSchema: z.ZodMiniType<
  SendEmailStatus,
  unknown
> = openEnums.inboundSchema(SendEmailStatus);

/** @internal */
export const SendEmailResponse$inboundSchema: z.ZodMiniType<
  SendEmailResponse,
  unknown
> = z.catchall(
  z.object({
    messageId: types.optional(types.string()),
    threadId: types.optional(types.string()),
    providerMessageId: types.optional(types.string()),
    status: types.optional(SendEmailStatus$inboundSchema),
  }),
  z.any(),
);

export function sendEmailResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendEmailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendEmailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendEmailResponse' from JSON`,
  );
}
