/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type TestInboxWebhookRequest = {
  id: string;
};

/**
 * Test webhook sent successfully
 */
export type TestInboxWebhookResponse = {
  ok?: boolean | undefined;
  message?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export type TestInboxWebhookRequest$Outbound = {
  id: string;
};

/** @internal */
export const TestInboxWebhookRequest$outboundSchema: z.ZodMiniType<
  TestInboxWebhookRequest$Outbound,
  TestInboxWebhookRequest
> = z.object({
  id: z.string(),
});

export function testInboxWebhookRequestToJSON(
  testInboxWebhookRequest: TestInboxWebhookRequest,
): string {
  return JSON.stringify(
    TestInboxWebhookRequest$outboundSchema.parse(testInboxWebhookRequest),
  );
}

/** @internal */
export const TestInboxWebhookResponse$inboundSchema: z.ZodMiniType<
  TestInboxWebhookResponse,
  unknown
> = z.catchall(
  z.object({
    ok: types.optional(types.boolean()),
    message: types.optional(types.string()),
  }),
  z.any(),
);

export function testInboxWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<TestInboxWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TestInboxWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TestInboxWebhookResponse' from JSON`,
  );
}
