/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateInboxRequestBody = {
  /**
   * Sender display name. Set null to clear.
   */
  displayName?: string | null | undefined;
  /**
   * URL to receive signed webhook events for this inbox. Set null to clear and revert to the account-level webhook. A signing secret is generated the first time a webhook URL is set on this inbox and returned once in the response body.
   */
  webhookUrl?: string | null | undefined;
};

export type UpdateInboxRequest = {
  id: string;
  body: UpdateInboxRequestBody;
};

/** @internal */
export type UpdateInboxRequestBody$Outbound = {
  displayName?: string | null | undefined;
  webhookUrl?: string | null | undefined;
};

/** @internal */
export const UpdateInboxRequestBody$outboundSchema: z.ZodMiniType<
  UpdateInboxRequestBody$Outbound,
  UpdateInboxRequestBody
> = z.object({
  displayName: z.optional(z.nullable(z.string())),
  webhookUrl: z.optional(z.nullable(z.string())),
});

export function updateInboxRequestBodyToJSON(
  updateInboxRequestBody: UpdateInboxRequestBody,
): string {
  return JSON.stringify(
    UpdateInboxRequestBody$outboundSchema.parse(updateInboxRequestBody),
  );
}

/** @internal */
export type UpdateInboxRequest$Outbound = {
  id: string;
  body: UpdateInboxRequestBody$Outbound;
};

/** @internal */
export const UpdateInboxRequest$outboundSchema: z.ZodMiniType<
  UpdateInboxRequest$Outbound,
  UpdateInboxRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => UpdateInboxRequestBody$outboundSchema),
});

export function updateInboxRequestToJSON(
  updateInboxRequest: UpdateInboxRequest,
): string {
  return JSON.stringify(
    UpdateInboxRequest$outboundSchema.parse(updateInboxRequest),
  );
}
