/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdatePodRequestBody = {
  /**
   * Your own identifier for this pod. Set null to clear.
   */
  clientId?: string | null | undefined;
  /**
   * Human-readable label. Set null to clear.
   */
  name?: string | null | undefined;
};

export type UpdatePodRequest = {
  /**
   * Pod ID or your own `clientId`
   */
  id: string;
  body: UpdatePodRequestBody;
};

/** @internal */
export type UpdatePodRequestBody$Outbound = {
  clientId?: string | null | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const UpdatePodRequestBody$outboundSchema: z.ZodMiniType<
  UpdatePodRequestBody$Outbound,
  UpdatePodRequestBody
> = z.object({
  clientId: z.optional(z.nullable(z.string())),
  name: z.optional(z.nullable(z.string())),
});

export function updatePodRequestBodyToJSON(
  updatePodRequestBody: UpdatePodRequestBody,
): string {
  return JSON.stringify(
    UpdatePodRequestBody$outboundSchema.parse(updatePodRequestBody),
  );
}

/** @internal */
export type UpdatePodRequest$Outbound = {
  id: string;
  body: UpdatePodRequestBody$Outbound;
};

/** @internal */
export const UpdatePodRequest$outboundSchema: z.ZodMiniType<
  UpdatePodRequest$Outbound,
  UpdatePodRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => UpdatePodRequestBody$outboundSchema),
});

export function updatePodRequestToJSON(
  updatePodRequest: UpdatePodRequest,
): string {
  return JSON.stringify(
    UpdatePodRequest$outboundSchema.parse(updatePodRequest),
  );
}
