/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type UpdateThreadRequestBody = {
  /**
   * Set to true to mark as read, false to mark as unread
   */
  isRead: boolean;
};

export type UpdateThreadRequest = {
  id: string;
  body: UpdateThreadRequestBody;
};

/**
 * Thread updated
 */
export type UpdateThreadResponse = {
  ok?: boolean | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export type UpdateThreadRequestBody$Outbound = {
  is_read: boolean;
};

/** @internal */
export const UpdateThreadRequestBody$outboundSchema: z.ZodMiniType<
  UpdateThreadRequestBody$Outbound,
  UpdateThreadRequestBody
> = z.pipe(
  z.object({
    isRead: z.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      isRead: "is_read",
    });
  }),
);

export function updateThreadRequestBodyToJSON(
  updateThreadRequestBody: UpdateThreadRequestBody,
): string {
  return JSON.stringify(
    UpdateThreadRequestBody$outboundSchema.parse(updateThreadRequestBody),
  );
}

/** @internal */
export type UpdateThreadRequest$Outbound = {
  id: string;
  body: UpdateThreadRequestBody$Outbound;
};

/** @internal */
export const UpdateThreadRequest$outboundSchema: z.ZodMiniType<
  UpdateThreadRequest$Outbound,
  UpdateThreadRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => UpdateThreadRequestBody$outboundSchema),
});

export function updateThreadRequestToJSON(
  updateThreadRequest: UpdateThreadRequest,
): string {
  return JSON.stringify(
    UpdateThreadRequest$outboundSchema.parse(updateThreadRequest),
  );
}

/** @internal */
export const UpdateThreadResponse$inboundSchema: z.ZodMiniType<
  UpdateThreadResponse,
  unknown
> = z.catchall(
  z.object({
    ok: types.optional(types.boolean()),
  }),
  z.any(),
);

export function updateThreadResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateThreadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateThreadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateThreadResponse' from JSON`,
  );
}
