/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Inbox = {
  /**
   * OpenMail inbox ID
   */
  id?: string | undefined;
  /**
   * ID of the pod this inbox belongs to. Inboxes created without an explicit pod land in your account's default pod.
   */
  podId?: string | undefined;
  /**
   * Full email address
   */
  address?: string | undefined;
  /**
   * Sender display name
   */
  displayName?: string | null | undefined;
  /**
   * URL that receives signed webhook events for this inbox, if set. Overrides the account-level webhook for this inbox only.
   */
  webhookUrl?: string | null | undefined;
  /**
   * Signing secret for this inbox's webhook. Only present in the response when the secret is generated or rotated (on create, on first setting a webhook URL, or via the rotate-secret endpoint) — it is never returned afterward.
   */
  webhookSecret?: string | null | undefined;
  createdAt?: Date | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const Inbox$inboundSchema: z.ZodMiniType<Inbox, unknown> = z.catchall(
  z.object({
    id: types.optional(types.string()),
    podId: types.optional(types.string()),
    address: types.optional(types.string()),
    displayName: z.optional(z.nullable(types.string())),
    webhookUrl: z.optional(z.nullable(types.string())),
    webhookSecret: z.optional(z.nullable(types.string())),
    createdAt: types.optional(types.date()),
  }),
  z.any(),
);

export function inboxFromJSON(
  jsonString: string,
): SafeParseResult<Inbox, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Inbox$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Inbox' from JSON`,
  );
}
