/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const MessageDirection = {
  Inbound: "inbound",
  Outbound: "outbound",
} as const;
export type MessageDirection = OpenEnum<typeof MessageDirection>;

/** @internal */
export const MessageDirection$inboundSchema: z.ZodMiniType<
  MessageDirection,
  unknown
> = openEnums.inboundSchema(MessageDirection);
/** @internal */
export const MessageDirection$outboundSchema: z.ZodMiniType<
  string,
  MessageDirection
> = openEnums.outboundSchema(MessageDirection);
