/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MessageDirection,
  MessageDirection$inboundSchema,
} from "./message-direction.js";

/**
 * Inbound only. to if your inbox was the main recipient; cc if you were copied on the email.
 */
export const DeliveryRole = {
  To: "to",
  Cc: "cc",
} as const;
/**
 * Inbound only. to if your inbox was the main recipient; cc if you were copied on the email.
 */
export type DeliveryRole = OpenEnum<typeof DeliveryRole>;

export type Attachment = {
  filename?: string | undefined;
  contentType?: string | undefined;
  sizeBytes?: number | undefined;
  /**
   * Signed URL for download
   */
  url?: string | undefined;
  [additionalProperties: string]: unknown;
};

export const Status = {
  Pending: "pending",
  Sent: "sent",
  Received: "received",
  Failed: "failed",
} as const;
export type Status = OpenEnum<typeof Status>;

export type Message = {
  id?: string | undefined;
  threadId?: string | undefined;
  direction?: MessageDirection | undefined;
  fromAddr?: string | undefined;
  /**
   * Your OpenMail inbox address for inbound messages. For outbound sends, the primary recipient.
   */
  toAddr?: string | undefined;
  /**
   * Inbound only. The address the sender wrote to (comma-separated if multiple). When deliveryRole is cc, reply to this address — not fromAddr.
   */
  headerTo?: string | null | undefined;
  /**
   * Inbound only. to if your inbox was the main recipient; cc if you were copied on the email.
   */
  deliveryRole?: DeliveryRole | null | undefined;
  /**
   * Email addresses copied on the message.
   */
  cc?: Array<string> | undefined;
  subject?: string | undefined;
  bodyText?: string | undefined;
  bodyHtml?: string | undefined;
  attachments?: Array<Attachment> | undefined;
  status?: Status | undefined;
  createdAt?: Date | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const DeliveryRole$inboundSchema: z.ZodMiniType<DeliveryRole, unknown> =
  openEnums.inboundSchema(DeliveryRole);

/** @internal */
export const Attachment$inboundSchema: z.ZodMiniType<Attachment, unknown> = z
  .catchall(
    z.object({
      filename: types.optional(types.string()),
      contentType: types.optional(types.string()),
      sizeBytes: types.optional(types.number()),
      url: types.optional(types.string()),
    }),
    z.any(),
  );

export function attachmentFromJSON(
  jsonString: string,
): SafeParseResult<Attachment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Attachment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Attachment' from JSON`,
  );
}

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<Status, unknown> = openEnums
  .inboundSchema(Status);

/** @internal */
export const Message$inboundSchema: z.ZodMiniType<Message, unknown> = z
  .catchall(
    z.object({
      id: types.optional(types.string()),
      threadId: types.optional(types.string()),
      direction: types.optional(MessageDirection$inboundSchema),
      fromAddr: types.optional(types.string()),
      toAddr: types.optional(types.string()),
      headerTo: z.optional(z.nullable(types.string())),
      deliveryRole: z.optional(z.nullable(DeliveryRole$inboundSchema)),
      cc: types.optional(z.array(types.string())),
      subject: types.optional(types.string()),
      bodyText: types.optional(types.string()),
      bodyHtml: types.optional(types.string()),
      attachments: types.optional(
        z.array(z.lazy(() => Attachment$inboundSchema)),
      ),
      status: types.optional(Status$inboundSchema),
      createdAt: types.optional(types.date()),
    }),
    z.any(),
  );

export function messageFromJSON(
  jsonString: string,
): SafeParseResult<Message, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Message$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Message' from JSON`,
  );
}
