/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Pod = {
  /**
   * OpenMail pod ID
   */
  id?: string | undefined;
  /**
   * Your own identifier for the pod, if set.
   */
  clientId?: string | null | undefined;
  /**
   * Human-readable label, if set.
   */
  name?: string | null | undefined;
  /**
   * Whether this is the account's default pod. Every account has exactly one; it is created automatically and cannot be deleted.
   */
  isDefault?: boolean | undefined;
  createdAt?: Date | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const Pod$inboundSchema: z.ZodMiniType<Pod, unknown> = z.catchall(
  z.object({
    id: types.optional(types.string()),
    clientId: z.optional(z.nullable(types.string())),
    name: z.optional(z.nullable(types.string())),
    isDefault: types.optional(types.boolean()),
    createdAt: types.optional(types.date()),
  }),
  z.any(),
);

export function podFromJSON(
  jsonString: string,
): SafeParseResult<Pod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pod' from JSON`,
  );
}
