/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Thread = {
  id?: string | undefined;
  subject?: string | undefined;
  /**
   * Whether the thread has been marked as read. Defaults to false for new inbound threads. Auto-set to true when a reply is sent.
   */
  isRead?: boolean | undefined;
  lastMessageAt?: Date | undefined;
  createdAt?: Date | undefined;
  messageCount?: number | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const Thread$inboundSchema: z.ZodMiniType<Thread, unknown> = z.catchall(
  z.object({
    id: types.optional(types.string()),
    subject: types.optional(types.string()),
    isRead: types.optional(types.boolean()),
    lastMessageAt: types.optional(types.date()),
    createdAt: types.optional(types.date()),
    messageCount: types.optional(types.number()),
  }),
  z.any(),
);

export function threadFromJSON(
  jsonString: string,
): SafeParseResult<Thread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Thread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Thread' from JSON`,
  );
}
